import test from "node:test";
import assert from "node:assert/strict";
import { CheckoutService } from "../src/checkoutService.js";
function service(decision){return new CheckoutService({hatp:{authorizePurchase:async()=>decision},now:()=>new Date("2026-08-21T03:00:00.000Z"),transactionId:()=>"tx-001"});}
test("executes only when HATP returns ALLOW",async()=>{const result=await service({decisionId:"d1",decision:"ALLOW",reason:"POLICY_ALLOWED"}).purchase({productId:"kbd-001"});assert.equal(result.status,"EXECUTED");assert.equal(result.hatp.decision,"ALLOW");});
test("keeps checkout pending when human verification is required",async()=>{const result=await service({decisionId:"d2",decision:"HUMAN_REQUIRED",reason:"AUTONOMOUS_LIMIT_EXCEEDED",requiredVerification:"PASSKEY_FIDO"}).purchase({productId:"monitor-001"});assert.equal(result.status,"PENDING_HUMAN");});
test("fails closed on DENY",async()=>{const result=await service({decisionId:"d3",decision:"DENY",reason:"AUTHORITY_ESCALATION"}).purchase({productId:"mouse-001",delegatedAuthorities:["READ_CATALOG"]});assert.equal(result.status,"BLOCKED");assert.equal(result.reason,"AUTHORITY_ESCALATION");});
test("fails closed when HATP is unavailable",async()=>{const s=new CheckoutService({hatp:{authorizePurchase:async()=>{throw new Error("offline")}},transactionId:()=>"tx-002"});const result=await s.purchase({productId:"mouse-001"});assert.equal(result.status,"BLOCKED");assert.equal(result.reason,"HATP_UNAVAILABLE_OR_INVALID");});
test("blocks local replay after an executed transaction",async()=>{const s=service({decisionId:"d4",decision:"ALLOW",reason:"POLICY_ALLOWED"});const first=await s.purchase({productId:"kbd-001",transactionId:"same-tx"});const replay=await s.purchase({productId:"kbd-001",transactionId:"same-tx"});assert.equal(first.status,"EXECUTED");assert.equal(replay.reason,"LOCAL_REPLAY_BLOCKED");});
